BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM*
#ARDUINO_LIBS = /home/theutheu/sketchbook/libraries/
ARDUINO_DIR = /usr/share/arduino

USER_LIB_PATH = /home/theutheu/sketchbook/libraries

include ../Arduino.mk